#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from syntax.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "syntax.y"

	int yylex(void);
	void yyerror(char *msg);

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	CHAR	258
#define	INT	259
#define	DOUBLE	260
#define	PROGRAM	261
#define	BOOL	262
#define	FOR	263
#define	TO	264
#define	DOWN	265
#define	WHILE	266
#define	IF	267
#define	THEN	268
#define	ELSE	269
#define	SWITCH	270
#define	CASE	271
#define	OF	272
#define	BREAK	273
#define	REPEAT	274
#define	CONTINUE	275
#define	RETURN	276
#define	WRITE	277
#define	READ	278
#define	TRUE	279
#define	FALSE	280
#define	IN	281
#define	END	282
#define	ID	283
#define	IntNumber	284
#define	RealNumber	285
#define	STRING	286
#define	CHARACTER	287
#define	LTE	288
#define	GTE	289
#define	EQU	290
#define	NEQ	291
#define	RANGE_DOTS	292
#define	LOGIC_AND	293
#define	LOGIC_OR	294
#define	UNTIL	295
#define	DO	296
#define	NEG	297


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int CHAR;
static const int INT;
static const int DOUBLE;
static const int PROGRAM;
static const int BOOL;
static const int FOR;
static const int TO;
static const int DOWN;
static const int WHILE;
static const int IF;
static const int THEN;
static const int ELSE;
static const int SWITCH;
static const int CASE;
static const int OF;
static const int BREAK;
static const int REPEAT;
static const int CONTINUE;
static const int RETURN;
static const int WRITE;
static const int READ;
static const int TRUE;
static const int FALSE;
static const int IN;
static const int END;
static const int ID;
static const int IntNumber;
static const int RealNumber;
static const int STRING;
static const int CHARACTER;
static const int LTE;
static const int GTE;
static const int EQU;
static const int NEQ;
static const int RANGE_DOTS;
static const int LOGIC_AND;
static const int LOGIC_OR;
static const int UNTIL;
static const int DO;
static const int NEG;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,CHAR=258
	,INT=259
	,DOUBLE=260
	,PROGRAM=261
	,BOOL=262
	,FOR=263
	,TO=264
	,DOWN=265
	,WHILE=266
	,IF=267
	,THEN=268
	,ELSE=269
	,SWITCH=270
	,CASE=271
	,OF=272
	,BREAK=273
	,REPEAT=274
	,CONTINUE=275
	,RETURN=276
	,WRITE=277
	,READ=278
	,TRUE=279
	,FALSE=280
	,IN=281
	,END=282
	,ID=283
	,IntNumber=284
	,RealNumber=285
	,STRING=286
	,CHARACTER=287
	,LTE=288
	,GTE=289
	,EQU=290
	,NEQ=291
	,RANGE_DOTS=292
	,LOGIC_AND=293
	,LOGIC_OR=294
	,UNTIL=295
	,DO=296
	,NEG=297


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::CHAR=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::DOUBLE=260;
const int YY_parse_CLASS::PROGRAM=261;
const int YY_parse_CLASS::BOOL=262;
const int YY_parse_CLASS::FOR=263;
const int YY_parse_CLASS::TO=264;
const int YY_parse_CLASS::DOWN=265;
const int YY_parse_CLASS::WHILE=266;
const int YY_parse_CLASS::IF=267;
const int YY_parse_CLASS::THEN=268;
const int YY_parse_CLASS::ELSE=269;
const int YY_parse_CLASS::SWITCH=270;
const int YY_parse_CLASS::CASE=271;
const int YY_parse_CLASS::OF=272;
const int YY_parse_CLASS::BREAK=273;
const int YY_parse_CLASS::REPEAT=274;
const int YY_parse_CLASS::CONTINUE=275;
const int YY_parse_CLASS::RETURN=276;
const int YY_parse_CLASS::WRITE=277;
const int YY_parse_CLASS::READ=278;
const int YY_parse_CLASS::TRUE=279;
const int YY_parse_CLASS::FALSE=280;
const int YY_parse_CLASS::IN=281;
const int YY_parse_CLASS::END=282;
const int YY_parse_CLASS::ID=283;
const int YY_parse_CLASS::IntNumber=284;
const int YY_parse_CLASS::RealNumber=285;
const int YY_parse_CLASS::STRING=286;
const int YY_parse_CLASS::CHARACTER=287;
const int YY_parse_CLASS::LTE=288;
const int YY_parse_CLASS::GTE=289;
const int YY_parse_CLASS::EQU=290;
const int YY_parse_CLASS::NEQ=291;
const int YY_parse_CLASS::RANGE_DOTS=292;
const int YY_parse_CLASS::LOGIC_AND=293;
const int YY_parse_CLASS::LOGIC_OR=294;
const int YY_parse_CLASS::UNTIL=295;
const int YY_parse_CLASS::DO=296;
const int YY_parse_CLASS::NEG=297;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		162
#define	YYFLAG		-32768
#define	YYNTBASE	61

#define YYTRANSLATE(x) ((unsigned)(x) <= 297 ? yytranslate[x] : 88)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    60,     2,     2,    56,
    57,    46,    44,    55,    45,    52,    47,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    59,    49,    43,
    58,    42,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    53,     2,    54,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    50,     2,    51,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    48
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     9,    12,    14,    16,    18,    21,    23,    26,    28,
    32,    34,    36,    38,    40,    42,    47,    50,    52,    56,
    58,    68,    70,    71,    75,    77,    80,    84,    85,    87,
    89,    96,   103,   108,   113,   120,   127,   129,   134,   136,
   139,   142,   147,   151,   155,   157,   162,   167,   169,   171,
   173,   175,   177,   179,   181,   183,   185,   187,   189,   191,
   193,   195,   196,   200,   202,   207,   209,   211,   213,   215,
   217,   219,   221,   223,   225,   229,   233,   236,   238,   242,
   246,   250,   255,   257
};

static const short yyrhs[] = {     6,
    28,    49,    62,    50,    75,    51,    52,     0,    63,    62,
     0,    63,     0,    65,     0,    64,     0,    71,    64,     0,
    71,     0,    66,    65,     0,    66,     0,    67,    69,    49,
     0,     4,     0,     5,     0,     7,     0,     3,     0,    28,
     0,    68,    53,    29,    54,     0,    68,    55,     0,    68,
     0,    28,    55,    70,     0,    28,     0,    67,    28,    56,
    72,    57,    50,    75,    51,    49,     0,    73,     0,     0,
    74,    49,    73,     0,    74,     0,    67,    70,     0,    76,
    49,    75,     0,     0,    86,     0,    65,     0,     8,    85,
    58,    86,    56,     9,     0,    10,     9,    57,    86,    41,
    87,     0,    11,    86,    41,    87,     0,    12,    86,    13,
    87,     0,    12,    86,    13,    87,    14,    87,     0,    15,
    86,    17,    50,    78,    51,     0,    18,     0,    19,    87,
    40,    86,     0,    20,     0,    21,    86,     0,    22,    83,
     0,    23,    56,    85,    57,     0,    86,    37,    86,     0,
    79,    78,    52,     0,    79,     0,    16,    86,    59,    87,
     0,    16,    77,    59,    87,     0,    38,     0,    39,     0,
    43,     0,    42,     0,    34,     0,    33,     0,    35,     0,
    36,     0,    44,     0,    45,     0,    46,     0,    47,     0,
    60,     0,    83,     0,     0,    86,    55,    83,     0,    86,
     0,    84,    53,    86,    54,     0,    28,     0,    28,     0,
    84,     0,    29,     0,    30,     0,    85,     0,    32,     0,
    24,     0,    25,     0,    86,    81,    86,     0,    86,    80,
    86,     0,    45,    86,     0,    31,     0,    56,    86,    57,
     0,    86,    26,    77,     0,    85,    58,    86,     0,    28,
    56,    82,    57,     0,    76,     0,    50,    75,    51,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    58,    61,    62,    65,    66,    69,    70,    73,    74,    77,
    80,    81,    82,    83,    86,    87,    90,    91,    94,    95,
    98,   101,   102,   105,   106,   109,   112,   113,   116,   117,
   118,   119,   120,   121,   122,   123,   124,   125,   126,   127,
   128,   129,   132,   135,   136,   139,   140,   143,   144,   145,
   146,   147,   148,   149,   150,   153,   154,   155,   156,   157,
   160,   161,   164,   165,   168,   169,   172,   173,   176,   177,
   178,   179,   180,   181,   182,   183,   184,   185,   186,   187,
   188,   189,   192,   193
};

static const char * const yytname[] = {   "$","error","$illegal.","CHAR","INT",
"DOUBLE","PROGRAM","BOOL","FOR","TO","DOWN","WHILE","IF","THEN","ELSE","SWITCH",
"CASE","OF","BREAK","REPEAT","CONTINUE","RETURN","WRITE","READ","TRUE","FALSE",
"IN","END","ID","IntNumber","RealNumber","STRING","CHARACTER","LTE","GTE","EQU",
"NEQ","RANGE_DOTS","LOGIC_AND","LOGIC_OR","UNTIL","DO","'>'","'<'","'+'","'-'",
"'*'","'/'","NEG","';'","'{'","'}'","'.'","'['","']'","','","'('","')'","'='",
"':'","'%'","Program","DecList","Dec","FuncDecs","VarDecs","VarDec","Type","IDDim",
"IDDList","IDList","FuncDec","ArgsList","ArgList","Arg","SList","Stmt","Range",
"Cases","Case","Logic","Aop","ExpList","ExpPlus","IDD","LValue","Exp","Block",
""
};
#endif

static const short yyr1[] = {     0,
    61,    62,    62,    63,    63,    64,    64,    65,    65,    66,
    67,    67,    67,    67,    68,    68,    69,    69,    70,    70,
    71,    72,    72,    73,    73,    74,    75,    75,    76,    76,
    76,    76,    76,    76,    76,    76,    76,    76,    76,    76,
    76,    76,    77,    78,    78,    79,    79,    80,    80,    80,
    80,    80,    80,    80,    80,    81,    81,    81,    81,    81,
    82,    82,    83,    83,    84,    84,    85,    85,    86,    86,
    86,    86,    86,    86,    86,    86,    86,    86,    86,    86,
    86,    86,    87,    87
};

static const short yyr2[] = {     0,
     8,     2,     1,     1,     1,     2,     1,     2,     1,     3,
     1,     1,     1,     1,     1,     4,     2,     1,     3,     1,
     9,     1,     0,     3,     1,     2,     3,     0,     1,     1,
     6,     6,     4,     4,     6,     6,     1,     4,     1,     2,
     2,     4,     3,     3,     1,     4,     4,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     0,     3,     1,     4,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     3,     3,     2,     1,     3,     3,
     3,     4,     1,     3
};

static const short yydefact[] = {     0,
     0,     0,     0,    14,    11,    12,    13,     0,     3,     5,
     4,     9,     0,     7,    28,     2,     8,     0,    15,    18,
     0,     6,     0,     0,     0,     0,     0,     0,    37,     0,
    39,     0,     0,     0,    73,    74,    66,    69,    70,    78,
    72,     0,     0,    30,     0,     0,    68,    71,    29,    15,
    23,     0,    17,    10,     0,    66,     0,     0,     0,     0,
     0,    28,    83,     0,    40,    41,    64,     0,    62,    77,
     0,     0,    28,     0,     0,     0,    53,    52,    54,    55,
    48,    49,    51,    50,    56,    57,    58,    59,    60,     0,
     0,     0,     0,    22,    25,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    61,    79,     1,    27,
     0,    81,    80,     0,    76,    75,    20,    26,     0,     0,
    16,     0,     0,    33,    34,     0,    84,    38,    63,    42,
    82,    65,     0,     0,    28,    24,     0,     0,     0,     0,
     0,    45,    43,    19,     0,    31,    32,    35,     0,     0,
    36,     0,     0,     0,     0,    44,    21,    47,    46,     0,
     0,     0
};

static const short yydefgoto[] = {   160,
     8,     9,    10,    44,    12,    18,    20,    21,   118,    14,
    93,    94,    95,    45,    63,   113,   141,   142,    90,    91,
   106,    66,    47,    48,    49,    64
};

static const short yypact[] = {     0,
   -11,   -28,   118,-32768,-32768,-32768,-32768,   -25,   118,-32768,
-32768,   118,    -1,   118,   132,-32768,-32768,     6,   -19,   -31,
   -21,-32768,    10,    18,    47,   405,   405,   405,-32768,    82,
-32768,   405,   405,     3,-32768,-32768,     4,-32768,-32768,-32768,
-32768,   405,   405,-32768,    11,    14,    12,    13,   381,-32768,
   118,    39,-32768,-32768,   -19,-32768,    19,     7,   204,    -3,
   148,   132,-32768,    32,   381,-32768,   227,    18,   405,    35,
   250,    23,   132,   405,   405,   405,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   405,
   405,    48,    26,-32768,    42,    30,   405,   405,    82,    82,
    38,    45,   405,   405,    41,    51,-32768,-32768,-32768,-32768,
   278,   381,-32768,   307,   381,   381,    44,-32768,    65,   118,
-32768,   330,   358,-32768,   103,   108,-32768,   381,-32768,-32768,
-32768,-32768,   405,    48,   132,-32768,   110,    82,    82,   405,
    75,   108,   381,-32768,    77,-32768,-32768,-32768,    70,   176,
-32768,    78,    84,    82,    82,-32768,-32768,-32768,-32768,   131,
   134,-32768
};

static const short yypgoto[] = {-32768,
   136,-32768,   127,    17,-32768,    -2,-32768,-32768,    15,-32768,
-32768,    28,-32768,   -57,   -15,    27,    16,-32768,-32768,-32768,
-32768,   -56,-32768,   -13,   -24,   -85
};


#define	YYLAST		461


static const short yytable[] = {    46,
    13,    59,    60,    61,   102,     1,    13,    65,    67,   100,
    57,    23,   107,   124,   125,   110,     2,    70,    71,    11,
     3,    52,    76,    53,    15,    11,    19,    54,    17,    77,
    78,    79,    80,    50,    81,    82,    51,    55,    83,    84,
    85,    86,    87,    88,    67,    56,    46,   129,    92,   111,
   112,   114,   147,   148,   105,    58,    89,    46,    68,    69,
    76,    72,    73,    98,    74,   115,   116,    96,   158,   159,
    75,   103,   122,   123,   109,   117,    97,   145,   128,    67,
    87,    88,   119,   121,     4,     5,     6,   126,     7,    24,
   120,    25,    26,    27,    89,   127,    28,   130,   134,    29,
    30,    31,    32,    33,    34,    35,    36,   131,   143,    37,
    38,    39,    40,    41,   135,   150,   139,    92,   146,    46,
     4,     5,     6,   140,     7,   151,    42,   153,   154,   156,
   161,    62,   157,   162,     4,     5,     6,    43,     7,    24,
    22,    25,    26,    27,    16,     0,    28,   136,   144,    29,
    30,    31,    32,    33,    34,    35,    36,   152,     0,    37,
    38,    39,    40,    41,   101,     0,   149,     0,     0,     0,
     0,     0,     0,    76,     0,     0,    42,     0,     0,     0,
    77,    78,    79,    80,     0,    81,    82,    43,     0,    83,
    84,    85,    86,    87,    88,     0,     0,     0,     0,     0,
     0,    76,     0,     0,     0,     0,     0,    89,    77,    78,
    79,    80,   133,    81,    82,     0,     0,    83,    84,    85,
    86,    87,    88,     0,     0,     0,     0,     0,     0,    76,
     0,     0,     0,     0,   155,    89,    77,    78,    79,    80,
     0,    81,    82,     0,    99,    83,    84,    85,    86,    87,
    88,     0,    76,     0,     0,     0,     0,     0,     0,    77,
    78,    79,    80,    89,    81,    82,     0,     0,    83,    84,
    85,    86,    87,    88,     0,    76,     0,     0,     0,     0,
     0,   104,    77,    78,    79,    80,    89,    81,    82,     0,
     0,    83,    84,    85,    86,    87,    88,     0,     0,     0,
     0,     0,     0,    76,     0,     0,   108,     0,     0,    89,
    77,    78,    79,    80,     0,    81,    82,     0,     0,    83,
    84,    85,    86,    87,    88,     0,     0,     0,     0,     0,
     0,   132,    76,     0,     0,     0,     0,    89,     0,    77,
    78,    79,    80,   133,    81,    82,     0,     0,    83,    84,
    85,    86,    87,    88,     0,    76,     0,     0,     0,     0,
     0,     0,    77,    78,    79,    80,    89,    81,    82,     0,
     0,    83,    84,    85,    86,    87,    88,     0,     0,     0,
     0,     0,     0,    76,     0,   137,     0,     0,     0,    89,
    77,    78,    79,    80,     0,    81,    82,     0,   138,    83,
    84,    85,    86,    87,    88,     0,    76,     0,     0,     0,
     0,     0,     0,    77,    78,    79,    80,    89,    81,    82,
     0,     0,    83,    84,    85,    86,    87,    88,    35,    36,
     0,     0,    37,    38,    39,    40,    41,     0,     0,     0,
    89,     0,     0,     0,     0,     0,     0,     0,     0,    42,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    43
};

static const short yycheck[] = {    15,
     3,    26,    27,    28,    62,     6,     9,    32,    33,    13,
    24,    14,    69,    99,   100,    73,    28,    42,    43,     3,
    49,    53,    26,    55,    50,     9,    28,    49,    12,    33,
    34,    35,    36,    28,    38,    39,    56,    28,    42,    43,
    44,    45,    46,    47,    69,    28,    62,   104,    51,    74,
    75,    76,   138,   139,    68,     9,    60,    73,    56,    56,
    26,    51,    49,    57,    53,    90,    91,    29,   154,   155,
    58,    40,    97,    98,    52,    28,    58,   135,   103,   104,
    46,    47,    57,    54,     3,     4,     5,    50,     7,     8,
    49,    10,    11,    12,    60,    51,    15,    57,    55,    18,
    19,    20,    21,    22,    23,    24,    25,    57,   133,    28,
    29,    30,    31,    32,    50,   140,    14,   120,     9,   135,
     3,     4,     5,    16,     7,    51,    45,    51,    59,    52,
     0,    50,    49,     0,     3,     4,     5,    56,     7,     8,
    14,    10,    11,    12,     9,    -1,    15,   120,   134,    18,
    19,    20,    21,    22,    23,    24,    25,   142,    -1,    28,
    29,    30,    31,    32,    17,    -1,   140,    -1,    -1,    -1,
    -1,    -1,    -1,    26,    -1,    -1,    45,    -1,    -1,    -1,
    33,    34,    35,    36,    -1,    38,    39,    56,    -1,    42,
    43,    44,    45,    46,    47,    -1,    -1,    -1,    -1,    -1,
    -1,    26,    -1,    -1,    -1,    -1,    -1,    60,    33,    34,
    35,    36,    37,    38,    39,    -1,    -1,    42,    43,    44,
    45,    46,    47,    -1,    -1,    -1,    -1,    -1,    -1,    26,
    -1,    -1,    -1,    -1,    59,    60,    33,    34,    35,    36,
    -1,    38,    39,    -1,    41,    42,    43,    44,    45,    46,
    47,    -1,    26,    -1,    -1,    -1,    -1,    -1,    -1,    33,
    34,    35,    36,    60,    38,    39,    -1,    -1,    42,    43,
    44,    45,    46,    47,    -1,    26,    -1,    -1,    -1,    -1,
    -1,    55,    33,    34,    35,    36,    60,    38,    39,    -1,
    -1,    42,    43,    44,    45,    46,    47,    -1,    -1,    -1,
    -1,    -1,    -1,    26,    -1,    -1,    57,    -1,    -1,    60,
    33,    34,    35,    36,    -1,    38,    39,    -1,    -1,    42,
    43,    44,    45,    46,    47,    -1,    -1,    -1,    -1,    -1,
    -1,    54,    26,    -1,    -1,    -1,    -1,    60,    -1,    33,
    34,    35,    36,    37,    38,    39,    -1,    -1,    42,    43,
    44,    45,    46,    47,    -1,    26,    -1,    -1,    -1,    -1,
    -1,    -1,    33,    34,    35,    36,    60,    38,    39,    -1,
    -1,    42,    43,    44,    45,    46,    47,    -1,    -1,    -1,
    -1,    -1,    -1,    26,    -1,    56,    -1,    -1,    -1,    60,
    33,    34,    35,    36,    -1,    38,    39,    -1,    41,    42,
    43,    44,    45,    46,    47,    -1,    26,    -1,    -1,    -1,
    -1,    -1,    -1,    33,    34,    35,    36,    60,    38,    39,
    -1,    -1,    42,    43,    44,    45,    46,    47,    24,    25,
    -1,    -1,    28,    29,    30,    31,    32,    -1,    -1,    -1,
    60,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    45,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    56
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 195 "syntax.y"


void yyerror(char *s) {
	fprintf(stderr, "%s\n", s);
}

int main(void) {
	yyparse();
	return 0;
}
